export enum EmploymentType {
  FULL_TIME = 'Full Time',
  PART_TIME = 'Part Time',
}

export enum EmploymentStatus {
  INTERNEE = 'Internee',
  PROBATION = 'Probation',
  PERMENANT = 'Permenant',
  TEMPORARY = 'Temporary',
}

export enum Degree {
  Associate = 'Associate',
  Bachelor = 'Bachelor',
  Master = 'Master',
  Doctorate = 'Doctorate',
  Diploma = 'Diploma',
  Certificate = 'Certificate',
  HighSchool = 'High School',
  PostGraduate = 'Post Graduate',
  Professional = 'Professional',
}

export enum JobRoles {
  SoftwareEngineer = 'Software Engineer',
  DataScientist = 'Data Scientist',
  ProductManager = 'Product Manager',
  GraphicDesigner = 'Graphic Designer',
  MarketingSpecialist = 'Marketing Specialist',
  SalesRepresentative = 'Sales Representative',
  HumanResources = 'Human Resources',
  ProjectManager = 'Project Manager',
  UXDesigner = 'UX Designer',
  SystemsAnalyst = 'Systems Analyst',
  BusinessAnalyst = 'Business Analyst',
  DevOpsEngineer = 'DevOps Engineer',
  CustomerSupport = 'Customer Support',
  FinancialAnalyst = 'Financial Analyst',
  NetworkAdministrator = 'Network Administrator',
  QualityAssurance = 'Quality Assurance',
  ITSupport = 'IT Support',
  ContentWriter = 'Content Writer',
  ResearchScientist = 'Research Scientist',
  LegalAdvisor = 'Legal Advisor',
  OperationsManager = 'Operations Manager',
  WebDeveloper = 'Web Developer',
  DatabaseAdministrator = 'Database Administrator',
  ElectricalEngineer = 'Electrical Engineer',
  MechanicalEngineer = 'Mechanical Engineer',
  CivilEngineer = 'Civil Engineer',
  Architect = 'Architect',
  SupplyChainManager = 'Supply Chain Manager',
  EventCoordinator = 'Event Coordinator',
  HealthcareAdministrator = 'Healthcare Administrator',
  TrainingSpecialist = 'Training Specialist',
  SocialMediaManager = 'Social Media Manager',
  PublicRelationsManager = 'Public Relations Manager',
  AdministrativeAssistant = 'Administrative Assistant',
  ExecutiveAssistant = 'Executive Assistant',
  LegalSecretary = 'Legal Secretary',
  ResearchAnalyst = 'Research Analyst',
  ProcurementSpecialist = 'Procurement Specialist',
  EnvironmentalConsultant = 'Environmental Consultant',
  SalesManager = 'Sales Manager',
  CustomerSuccessManager = 'Customer Success Manager',
  DigitalMarketingManager = 'Digital Marketing Manager',
  RiskManager = 'Risk Manager',
  StrategicPlanner = 'Strategic Planner',
  OperationsAnalyst = 'Operations Analyst',
  QualityControlManager = 'Quality Control Manager',
  TaxAdvisor = 'Tax Advisor',
  CompensationAnalyst = 'Compensation Analyst',
  ProductDesigner = 'Product Designer',
  ScrumMaster = 'Scrum Master',
  NetworkEngineer = 'Network Engineer',
  BlockchainDeveloper = 'Blockchain Developer',
  CloudEngineer = 'Cloud Engineer',
}

export enum Gender {
  MALE = 'Male',
  FEMALE = 'Female',
}

export enum WorkSide {
  REMOTE = 'Remote',
  ON_SITE = 'On Site',
  HYBRID = 'Hybrid',
}

export enum Skills {
  JAVA_SCRIPT = 'JavaScript',
  PYTHON = 'Python',
  JAVA = 'Java',
  C_SHARP = 'C#',
  C_PLUS_PLUS = 'C++',
  RUBY = 'Ruby',
  PHP = 'PHP',
  SWIFT = 'Swift',
  KOTLIN = 'Kotlin',
  TYPE_SCRIPT = 'TypeScript',

  HTML = 'HTML',
  CSS = 'CSS',
  REACT = 'React',
  ANGULAR = 'Angular',
  VUE = 'Vue',
  NODE_JS = 'Node.js',
  EXPRESS = 'Express',
  BOOTSTRAP = 'Bootstrap',
  SASS = 'Sass',

  SQL = 'SQL',
  MONGO_DB = 'MongoDB',
  POSTGRE_SQL = 'PostgreSQL',
  MY_SQL = 'MySQL',
  ORACLE_DB = 'OracleDB',
  REDIS = 'Redis',
  DATA_ANALYSIS = 'Data Analysis',
  DATA_VISUALIZATION = 'Data Visualization',

  AWS = 'AWS',
  AZURE = 'Azure',
  GOOGLE_CLOUD = 'Google Cloud',
  DOCKER = 'Docker',
  KUBERNETES = 'Kubernetes',
  JENKINS = 'Jenkins',
  CI_CD = 'CI/CD',
  TERRAFORM = 'Terraform',

  AGILE = 'Agile',
  SCRUM = 'Scrum',
  KANBAN = 'Kanban',
  TEST_DRIVEN_DEVELOPMENT = 'Test-Driven Development',
  CONTINUOUS_INTEGRATION = 'Continuous Integration',

  GIT = 'Git',
  GITHUB = 'GitHub',
  GITLAB = 'GitLab',
  BITBUCKET = 'Bitbucket',
  JIRA = 'JIRA',
  TRELLO = 'Trello',
  ASANA = 'Asana',
  SLACK = 'Slack',
  ZOOM = 'Zoom',
  MICROSOFT_TEAMS = 'Microsoft Teams',

  ADOBE_PHOTOSHOP = 'Adobe Photoshop',
  ADOBE_ILLUSTRATOR = 'Adobe Illustrator',
  ADOBE_XD = 'Adobe XD',
  FIGMA = 'Figma',
  SKETCH = 'Sketch',
  INVISION = 'InVision',

  GOOGLE_ANALYTICS = 'Google Analytics',
  SEMRUSH = 'SEMrush',
  MOZ = 'Moz',
  HUBSPOT = 'HubSpot',
  HOOTSUITE = 'Hootsuite',
  MAILCHIMP = 'Mailchimp',

  PROJECT_MANAGEMENT = 'Project Management',
  STRATEGIC_PLANNING = 'Strategic Planning',
  BUSINESS_ANALYSIS = 'Business Analysis',
  FINANCIAL_ANALYSIS = 'Financial Analysis',
  RISK_MANAGEMENT = 'Risk Management',
  NEGOTIATION = 'Negotiation',
  LEADERSHIP = 'Leadership',

  COMMUNICATION = 'Communication',
  TEAMWORK = 'Teamwork',
  PROBLEM_SOLVING = 'Problem Solving',
  ADAPTABILITY = 'Adaptability',
  TIME_MANAGEMENT = 'Time Management',
  CONFLICT_RESOLUTION = 'Conflict Resolution',

  CUSTOMER_SUPPORT = 'Customer Support',
  CRM = 'CRM',
  CUSTOMER_RELATIONSHIP_MANAGEMENT = 'Customer Relationship Management',
  HELP_DESK = 'Help Desk',

  LEGAL_COMPLIANCE = 'Legal Compliance',
  EVENT_PLANNING = 'Event Planning',
  RESEARCH = 'Research',
  LANGUAGE_TRANSLATION = 'Language Translation',
  SUPPLY_CHAIN_MANAGEMENT = 'Supply Chain Management',
}
